# ottrent settings
APPLICATION_PATH_LOG = 'C:/Users/omza/source/repos/otrrentserver/'
APPLICATION_LOGLEVEL_CONSOLE = 10 # debug 
APPLICATION_LOGLEVEL_FILE = 10 # debug
APPLICATION_LOG_LEVEL = 10 # Debug
APPLICATION_MAINLOGGER = 'otrrentetl'
APPLICATION_ETL_INTERVAL = 3624
APPLICATION_QUEUE_INTERVAL = 300

